language: node_js
node_js:
  #- "node" # latest
  - "6"
script:
  - node tests/http_status.js
  - node tests/index_complete.js
cache:
  directories:
    - node_modules # cache NPM dependencies
git:
  depth: 3 # makes cloning faster