language: node_js
node_js:
  #- "node" # latest
  - "6"
env:
  - TESTFILE=tests/fixtures_valid.js
  - TESTFILE=tests/http_status.js
  - TESTFILE=tests/register_correct.js
script:
  - NODE_ENV=production node "$TESTFILE"
cache:
  directories:
    - node_modules # cache NPM dependencies
git:
  depth: 3 # makes cloning faster