name: Lighthouse
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'component-ui')
    env:
      NODE_ENV: production
      ALLOW_SEARCH_INDEXING: allowed
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js v14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run the Lighthouse CI
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            http://localhost:5000/
            http://localhost:5000/chroma-q/color-force-ii-72
            http://localhost:5000/categories/Color%20Changer
          runs: 3
          configPath: '.github/lighthouserc.js'
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Post Lighthouse Status
        uses: manrueda/lighthouse-report-action@v1.1.2
        with:
          reports: '.lighthouseci'
          github-token: ${{ secrets.GITHUB_TOKEN }}
