name: Lighthouse
on:
  push:
    branches-ignore:
      - master
  schedule:
    - cron: '30 18 * * *' # everyday 18:30 UTC
  workflow_dispatch:
jobs:
  review:
    name: Review
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js v14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run the Lighthouse CI
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            http://localhost:5000/
            http://localhost:5000/chroma-q/color-force-ii-72
            http://localhost:5000/categories/Color%20Changer
          runs: 3
          configPath: '.github/lighthouserc.js'
          uploadArtifacts: true
          temporaryPublicStorage: true
  production:
    name: Production
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run the Lighthouse CI
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://open-fixture-library.org/
            https://open-fixture-library.org/chroma-q/color-force-ii-72
            https://open-fixture-library.org/categories/Color%20Changer
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
