name: Lint and test
on: pull_request

jobs:
  test:
    name: Test with Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint -- --format compact
